version: '3'

services:
  db:
    image: "quay.io/inframine/e-logs:db"
    hostname: "db"
    ports:
     - "1433:1433"
  redis:
    image: "redis"
    hostname: "redis"
    ports:
     - "6379:6379"
  web:
    build: .
    ports:
      - "8085:8085"
      - "8000:8000"
      - "80:80"
      - "443:443"
    command: bash -c "./docker/entrypoint.sh"
    environment:
      - CADDY_HOSTNAME=elogs.online
    depends_on:
     - redis
     - db
    restart: on-failure
  celery:
   build: .
   command: celery -A e_logs.common.all_journals_app.tasks worker --loglevel=info
   environment:
    - C_FORCE_ROOT=true
   depends_on:
    - db
    - redis
    - web
   restart: on-failure
  celery-beat:
   build: .
   command: celery -A e_logs.common.all_journals_app.tasks beat --loglevel=info --scheduler=django_celery_beat.schedulers:DatabaseScheduler
   depends_on:
    - db
    - redis
    - web
   restart: on-failure

